-- Seed inicial del catálogo (categorías y productos)
-- Usa INSERT OR IGNORE para permitir re-ejecución sin duplicados.

INSERT OR IGNORE INTO categories (id, name, description) VALUES
  (1, 'Juegos de mesa', 'Juegos de mesa para todos los públicos'),
  (2, 'Juegos PC', 'Juegos para ordenador (PC)'),
  (3, 'Juegos XBOX', 'Juegos para consolas Xbox'),
  (4, 'Juegos Nintendo', 'Juegos para consolas Nintendo'),
  (5, 'Juegos PlayStation 5', 'Juegos para PlayStation 5');

INSERT OR IGNORE INTO products (
  id,
  category_id,
  name,
  short_description,
  long_description,
  price,
  image,
  genre,
  developer,
  players,
  release_date,
  in_stock,
  rating
) VALUES
  (
    1,
    1,
    'Catan',
    'Juego de estrategia y comercio',
    'Catan es un juego de estrategia clásico donde los jugadores compiten por construir asentamientos, ciudades y carreteras en una isla. Cada turno implica comerciar recursos con otros jugadores, haciendo que sea un juego dinámico y social.',
    34.99,
    'https://via.placeholder.com/300x300?text=Catan',
    'Estrategia, Negociación',
    NULL,
    '2-4 jugadores',
    '1995',
    1,
    4.8
  ),
  (
    2,
    1,
    'Carcassonne',
    'Juego de colocación de losetas',
    'Carcassonne es un juego de construcción de paisajes medievales mediante la colocación de losetas. Los jugadores crean caminos, ciudades y monasterios mientras compiten por puntos. Es un juego accesible pero con profundidad estratégica.',
    24.99,
    'https://via.placeholder.com/300x300?text=Carcassonne',
    'Colocación de losetas, Construcción',
    NULL,
    '2-5 jugadores',
    '2000',
    1,
    4.7
  ),
  (
    3,
    2,
    'Cyberpunk 2077 (PC)',
    'RPG de mundo abierto futurista',
    'Cyberpunk 2077 es un RPG de acción en primera persona ambientado en el futuro distópico de 2077. Crea tu personaje y sumérgete en la megaciudad de Night City, donde tus acciones y decisiones moldean tu historia única.',
    29.99,
    'https://via.placeholder.com/300x300?text=Cyberpunk+2077',
    'RPG, Acción, Ciencia Ficción',
    'CD Projekt Red',
    NULL,
    '2020',
    1,
    4.5
  ),
  (
    4,
    2,
    'Baldur''s Gate 3 (PC)',
    'RPG táctico profundo basado en D&D',
    'Baldur''s Gate 3 es un RPG de rol táctico que trae la magia de Dungeons & Dragons al mundo digital. Con miles de posibilidades narrativas y batallas estratégicas, cada decisión importa en esta épica aventura.',
    49.99,
    'https://via.placeholder.com/300x300?text=Baldurs+Gate+3',
    'RPG, Estrategia por turnos, Fantasía',
    'Larian Studios',
    NULL,
    '2023',
    1,
    4.9
  ),
  (
    5,
    3,
    'Halo Infinite (Xbox)',
    'Shooter épico de ciencia ficción',
    'Halo Infinite es un shooter en primera persona que lleva la franquicia a nuevas alturas. Pilota el Grappling Hook, personaliza tu arsenal y domina los campos de batalla en este juego multijugador intenso con una campaña épica.',
    39.99,
    'https://via.placeholder.com/300x300?text=Halo+Infinite',
    'Shooter, Acción, Ciencia Ficción',
    '343 Industries',
    NULL,
    '2021',
    1,
    4.6
  ),
  (
    6,
    3,
    'Forza Horizon 5 (Xbox)',
    'Juego de carreras en mundo abierto',
    'Forza Horizon 5 te lleva a México con gráficos impresionantes y una colección de 500+ vehículos. Explora paisajes diversos, participa en carreras emocionantes y personaliza tu experiencia de conducción.',
    59.99,
    'https://via.placeholder.com/300x300?text=Forza+Horizon+5',
    'Carreras, Mundo abierto',
    'Playground Games',
    NULL,
    '2021',
    1,
    4.8
  ),
  (
    7,
    4,
    'The Legend of Zelda: Tears of the Kingdom',
    'Aventura épica de exploración',
    'En Tears of the Kingdom, Link regresa para una aventura aún más épica. Explora un mundo vasto lleno de secretos, resuelve acertijos creativos y enfrenta enemigos poderosos. La libertad y la exploración son el corazón de esta obra maestra.',
    69.99,
    'https://via.placeholder.com/300x300?text=Zelda+Tears',
    'Aventura, Acción, Puzzle',
    'Nintendo EPD',
    NULL,
    '2023',
    1,
    4.9
  ),
  (
    8,
    4,
    'Mario Kart 8 Deluxe',
    'Carreras arcade arcade con personajes icónicos',
    'Mario Kart 8 Deluxe es la versión definitiva del clásico juego de carreras. Compite contra amigos o la IA en circuitos creativos, usa power-ups estratégicos y disfruta del caos arcade que Nintendo hace mejor.',
    59.99,
    'https://via.placeholder.com/300x300?text=Mario+Kart+8',
    'Carreras, Arcade',
    'Nintendo EAD',
    NULL,
    '2014',
    1,
    4.8
  ),
  (
    9,
    5,
    'Marvel''s Spider-Man 2 (PS5)',
    'Aventura de superhéroes en Nueva York',
    'Experiencia una historia épica de Spider-Man con gráficos de siguiente generación. Controla a Peter Parker y Miles Morales mientras proteges Nueva York de nuevas amenazas en este emocionante juego de acción y aventura.',
    69.99,
    'https://via.placeholder.com/300x300?text=Spider-Man+2',
    'Acción, Aventura, Superhéroes',
    'Insomniac Games',
    NULL,
    '2023',
    1,
    4.8
  ),
  (
    10,
    5,
    'Demon''s Souls (PS5)',
    'RPG de acción desafiante',
    'Demon''s Souls es un remake espectacular del clásico de PS3. Enfrenta enemigos desafiantes, mejora tus habilidades y derrota poderosos jefes en este juego que requiere habilidad, estrategia y perseverancia.',
    49.99,
    'https://via.placeholder.com/300x300?text=Demons+Souls',
    'RPG de acción, Souls-like',
    'Bluepoint Games',
    NULL,
    '2020',
    1,
    4.7
  );
