-- SEED: Tabla categories
DELETE FROM categories;
DELETE FROM sqlite_sequence WHERE name = 'categories';
INSERT OR IGNORE INTO categories (id, name, description) VALUES
  (1, 'Juegos de mesa', 'Juegos de mesa para todos los públicos'),
  (2, 'Juegos PC', 'Juegos para ordenador (PC)'),
  (3, 'Juegos XBOX', 'Juegos para consolas Xbox'),
  (4, 'Juegos Nintendo', 'Juegos para consolas Nintendo'),
  (5, 'Juegos PlayStation 5', 'Juegos para PlayStation 5'),
  (6, 'Juegos de cartas', 'Juegos de cartas coleccionables y tradicionales'),
  (7, 'Juegos de rol', 'Juegos de rol de mesa y digitales'),
  (8, 'Juegos móviles', 'Juegos para dispositivos móviles'),
  (9, 'Juegos retro', 'Juegos clásicos y consolas antiguas'),
  (10, 'Accesorios', 'Accesorios para juegos y consolas');

-- SEED: Tabla products
DELETE FROM products;
DELETE FROM sqlite_sequence WHERE name = 'products';
INSERT OR IGNORE INTO products (
  id,
  category_id,
  name,
  short_description,
  long_description,
  price,
  image,
  genre,
  developer,
  players,
  release_date,
  in_stock,
  rating
) VALUES
-- Categoría 1: Juegos de mesa
(1, 1, 'Catan', 'Juego de estrategia y comercio', 'Catan es un juego de estrategia clásico donde los jugadores compiten por construir asentamientos, ciudades y carreteras en una isla. Cada turno implica comerciar recursos con otros jugadores, haciendo que sea un juego dinámico y social.', 34.99, 'https://via.placeholder.com/300x300?text=Catan', 'Estrategia', NULL, '2-4 jugadores', '1995', 1, 4.8),
(2, 1, 'Carcassonne', 'Juego de colocación de losetas', 'Carcassonne es un juego de construcción de paisajes medievales mediante la colocación de losetas. Los jugadores crean caminos, ciudades y monasterios mientras compiten por puntos. Es un juego accesible pero con profundidad estratégica.', 24.99, 'https://via.placeholder.com/300x300?text=Carcassonne', 'Colocación de losetas', NULL, '2-5 jugadores', '2000', 1, 4.7),
(3, 1, 'Risk', 'Juego de conquista mundial', 'Risk es un juego de estrategia militar donde los jugadores compiten por conquistar el mundo. Cada turno implica mover tropas y construir fortificaciones.', 29.99, 'https://via.placeholder.com/300x300?text=Risk', 'Estrategia', NULL, '2-6 jugadores', '1959', 1, 4.6),
(4, 1, 'Monopoly', 'Juego de finanzas y propiedades', 'Monopoly es un clásico de compra y venta de propiedades. Los jugadores construyen y desarrollan sus propiedades para obtener rentas.', 19.99, 'https://via.placeholder.com/300x300?text=Monopoly', 'Finanzas', NULL, '2-8 jugadores', '1935', 1, 4.5),
(5, 1, 'Dixit', 'Juego de cartas ilustradas', 'Dixit es un juego de creatividad e imaginación. Los jugadores describen imágenes que otros deben adivinar.', 21.99, 'https://via.placeholder.com/300x300?text=Dixit', 'Creatividad', NULL, '3-6 jugadores', '2008', 1, 4.7),
(6, 1, '7 Wonders', 'Juego de civilizaciones', 'Construye una civilización y compite por puntos. Cada jugador construye una civilización y gana puntos por sus logros.', 27.99, 'https://via.placeholder.com/300x300?text=7+Wonders', 'Civilización', NULL, '2-7 jugadores', '2010', 1, 4.6),
(7, 1, 'Aventureros al Tren', 'Juego de trenes y rutas', 'Conecta ciudades y gana puntos. Los jugadores construyen rutas y conectan ciudades.', 32.99, 'https://via.placeholder.com/300x300?text=Aventureros+al+Tren', 'Rutas', NULL, '2-5 jugadores', '2004', 1, 4.8),
(8, 1, 'Jungle Speed', 'Juego de reflejos', 'Sé el más rápido en atrapar el tótem. Los jugadores deben atrapar el tótem antes que el otro.', 14.99, 'https://via.placeholder.com/300x300?text=Jungle+Speed', 'Reflejos', NULL, '2-10 jugadores', '1997', 1, 4.4),
(9, 1, 'Virus!', 'Juego de cartas de virus', 'Compite por erradicar virus en tu cuerpo. Los jugadores deben atrapar virus antes que el otro.', 13.99, 'https://via.placeholder.com/300x300?text=Virus', 'Cartas', NULL, '2-6 jugadores', '2015', 1, 4.5),
(10, 1, 'Código Secreto', 'Juego de palabras y espías', 'Adivina las palabras clave de tu equipo. Los jugadores deben adivinar palabras clave.', 18.99, 'https://via.placeholder.com/300x300?text=Codigo+Secreto', 'Palabras', NULL, '2-8 jugadores', '2015', 1, 4.7),
-- Categoría 2: Juegos PC
(11, 2, 'Cyberpunk 2077', 'RPG futurista', 'Cyberpunk 2077 es un RPG de acción en primera persona ambientado en el futuro distópico de 2077. Crea tu personaje y sumérgete en la megaciudad de Night City, donde tus acciones y decisiones moldean tu historia única.', 29.99, 'https://via.placeholder.com/300x300?text=Cyberpunk+2077', 'RPG', 'CD Projekt Red', '1 jugador', '2020', 1, 4.5),
(12, 2, 'Baldur''s Gate 3', 'RPG táctico', 'Baldur''s Gate 3 es un RPG de rol táctico que trae la magia de Dungeons & Dragons al mundo digital. Con miles de posibilidades narrativas y batallas estratégicas, cada decisión importa en esta épica aventura.', 49.99, 'https://via.placeholder.com/300x300?text=Baldurs+Gate+3', 'RPG', 'Larian Studios', '1-4 jugadores', '2023', 1, 4.9),
(13, 2, 'The Witcher 3', 'Aventura de fantasía', 'The Witcher 3 es un RPG de mundo abierto...', 19.99, 'https://via.placeholder.com/300x300?text=Witcher+3', 'RPG', 'CD Projekt Red', '1 jugador', '2015', 1, 4.9),
(14, 2, 'Minecraft', 'Sandbox creativo', 'Minecraft permite construir y explorar...', 26.95, 'https://via.placeholder.com/300x300?text=Minecraft', 'Sandbox', 'Mojang', '1-8 jugadores', '2011', 1, 4.8),
(15, 2, 'League of Legends', 'MOBA competitivo', 'League of Legends es un MOBA popular...', 0.00, 'https://via.placeholder.com/300x300?text=LoL', 'MOBA', 'Riot Games', '1-10 jugadores', '2009', 1, 4.7),
(16, 2, 'Valorant', 'Shooter táctico', 'Valorant es un shooter competitivo...', 0.00, 'https://via.placeholder.com/300x300?text=Valorant', 'Shooter', 'Riot Games', '1-10 jugadores', '2020', 1, 4.6),
(17, 2, 'Age of Empires IV', 'Estrategia en tiempo real', 'Construye imperios y conquista...', 59.99, 'https://via.placeholder.com/300x300?text=AoE+IV', 'Estrategia', 'Relic', '1-8 jugadores', '2021', 1, 4.5),
(18, 2, 'Counter-Strike 2', 'Shooter competitivo', 'CS2 es la nueva generación de Counter-Strike...', 0.00, 'https://via.placeholder.com/300x300?text=CS2', 'Shooter', 'Valve', '1-10 jugadores', '2023', 1, 4.8),
(19, 2, 'Stardew Valley', 'Simulación de granja', 'Crea tu granja y haz amigos...', 13.99, 'https://via.placeholder.com/300x300?text=Stardew+Valley', 'Simulación', 'ConcernedApe', '1-4 jugadores', '2016', 1, 4.9),
(20, 2, 'Terraria', 'Aventura sandbox', 'Explora, construye y combate...', 9.99, 'https://via.placeholder.com/300x300?text=Terraria', 'Sandbox', 'Re-Logic', '1-8 jugadores', '2011', 1, 4.7),
-- Categoría 3: Juegos XBOX
(21, 3, 'Halo Infinite', 'Shooter épico', 'Halo Infinite es un shooter en primera persona que lleva la franquicia a nuevas alturas. Pilota el Grappling Hook, personaliza tu arsenal y domina los campos de batalla en este juego multijugador intenso con una campaña épica.', 39.99, 'https://via.placeholder.com/300x300?text=Halo+Infinite', 'Shooter', '343 Industries', '1-12 jugadores', '2021', 1, 4.6),
(22, 3, 'Forza Horizon 5', 'Carreras en mundo abierto', 'Forza Horizon 5 te lleva a México con gráficos impresionantes y una colección de 500+ vehículos. Explora paisajes diversos, participa en carreras emocionantes y personaliza tu experiencia de conducción.', 59.99, 'https://via.placeholder.com/300x300?text=Forza+Horizon+5', 'Carreras', 'Playground Games', '1-12 jugadores', '2021', 1, 4.8),
(23, 3, 'Gears 5', 'Shooter cooperativo', 'Gears 5 es un shooter de acción...', 29.99, 'https://via.placeholder.com/300x300?text=Gears+5', 'Shooter', 'The Coalition', '1-5 jugadores', '2019', 1, 4.5),
(24, 3, 'Sea of Thieves', 'Aventura pirata', 'Sea of Thieves es un juego de piratas...', 39.99, 'https://via.placeholder.com/300x300?text=Sea+of+Thieves', 'Aventura', 'Rare', '1-4 jugadores', '2018', 1, 4.7),
(25, 3, 'Ori and the Will of the Wisps', 'Plataformas artístico', 'Ori es un juego de plataformas...', 19.99, 'https://via.placeholder.com/300x300?text=Ori', 'Plataformas', 'Moon Studios', '1 jugador', '2020', 1, 4.9),
(26, 3, 'FIFA 24', 'Fútbol competitivo', 'FIFA 24 es la última entrega de fútbol...', 69.99, 'https://via.placeholder.com/300x300?text=FIFA+24', 'Deportes', 'EA Sports', '1-4 jugadores', '2024', 1, 4.4),
(27, 3, 'Cuphead', 'Plataformas desafiante', 'Cuphead es un juego de plataformas...', 19.99, 'https://via.placeholder.com/300x300?text=Cuphead', 'Plataformas', 'Studio MDHR', '1-2 jugadores', '2017', 1, 4.8),
(28, 3, 'Flight Simulator', 'Simulación de vuelo', 'Pilota aviones en todo el mundo...', 59.99, 'https://via.placeholder.com/300x300?text=Flight+Simulator', 'Simulación', 'Asobo Studio', '1 jugador', '2020', 1, 4.7),
(29, 3, 'Minecraft Dungeons', 'Aventura cooperativa', 'Explora mazmorras con amigos...', 19.99, 'https://via.placeholder.com/300x300?text=Minecraft+Dungeons', 'Aventura', 'Mojang', '1-4 jugadores', '2020', 1, 4.5),
(30, 3, 'Forza Motorsport', 'Simulación de carreras', 'Compite en circuitos realistas...', 69.99, 'https://via.placeholder.com/300x300?text=Forza+Motorsport', 'Carreras', 'Turn 10', '1-24 jugadores', '2023', 1, 4.6),
-- Categoría 4: Juegos Nintendo
(31, 4, 'The Legend of Zelda: Tears of the Kingdom', 'Aventura épica de exploración', 'En Tears of the Kingdom, Link regresa para una aventura aún más épica. Explora un mundo vasto lleno de secretos, resuelve acertijos creativos y enfrenta enemigos poderosos. La libertad y la exploración son el corazón de esta obra maestra.', 69.99, 'https://via.placeholder.com/300x300?text=Zelda+Tears', 'Aventura', 'Nintendo EPD', '1 jugador', '2023', 1, 4.9),
(32, 4, 'Mario Kart 8 Deluxe', 'Carreras arcade arcade con personajes icónicos', 'Mario Kart 8 Deluxe es la versión definitiva del clásico juego de carreras. Compite contra amigos o la IA en circuitos creativos, usa power-ups estratégicos y disfruta del caos arcade que Nintendo hace mejor.', 59.99, 'https://via.placeholder.com/300x300?text=Mario+Kart+8', 'Carreras', 'Nintendo EAD', '1-4 jugadores', '2014', 1, 4.8),
(33, 4, 'Super Smash Bros. Ultimate', 'Lucha crossover', 'Super Smash Bros. reúne a personajes...', 59.99, 'https://via.placeholder.com/300x300?text=Smash+Bros', 'Lucha', 'Nintendo', '1-8 jugadores', '2018', 1, 4.9),
(34, 4, 'Animal Crossing: New Horizons', 'Simulación social', 'Crea tu isla y haz amigos...', 49.99, 'https://via.placeholder.com/300x300?text=Animal+Crossing', 'Simulación', 'Nintendo', '1-4 jugadores', '2020', 1, 4.8),
(35, 4, 'Splatoon 3', 'Shooter colorido', 'Splatoon 3 es un shooter multijugador...', 59.99, 'https://via.placeholder.com/300x300?text=Splatoon+3', 'Shooter', 'Nintendo', '1-8 jugadores', '2022', 1, 4.7),
(36, 4, 'Pokémon Escarlata', 'RPG de monstruos', 'Atrapa y entrena Pokémon...', 59.99, 'https://via.placeholder.com/300x300?text=Pokemon+Escarlata', 'RPG', 'Game Freak', '1-4 jugadores', '2022', 1, 4.6),
(37, 4, 'Luigi''s Mansion 3', 'Aventura de fantasmas', 'Ayuda a Luigi a rescatar a sus amigos...', 49.99, 'https://via.placeholder.com/300x300?text=Luigis+Mansion+3', 'Aventura', 'Nintendo', '1-2 jugadores', '2019', 1, 4.7),
(38, 4, 'Fire Emblem Engage', 'Estrategia táctica', 'Lidera tu ejército en batallas tácticas...', 59.99, 'https://via.placeholder.com/300x300?text=Fire+Emblem+Engage', 'Estrategia', 'Intelligent Systems', '1 jugador', '2023', 1, 4.5),
(39, 4, 'Kirby and the Forgotten Land', 'Plataformas 3D', 'Explora mundos con Kirby...', 59.99, 'https://via.placeholder.com/300x300?text=Kirby', 'Plataformas', 'HAL Laboratory', '1-2 jugadores', '2022', 1, 4.8),
(40, 4, 'Mario Party Superstars', 'Fiesta multijugador', 'Disfruta de minijuegos clásicos...', 59.99, 'https://via.placeholder.com/300x300?text=Mario+Party', 'Fiesta', 'NDcube', '1-4 jugadores', '2021', 1, 4.6),
-- Categoría 5: Juegos PlayStation 5
(41, 5, 'Marvel''s Spider-Man 2 (PS5)', 'Aventura de superhéroes en Nueva York', 'Experiencia una historia épica de Spider-Man con gráficos de siguiente generación. Controla a Peter Parker y Miles Morales mientras proteges Nueva York de nuevas amenazas en este emocionante juego de acción y aventura.', 69.99, 'https://via.placeholder.com/300x300?text=Spider-Man+2', 'Acción, Aventura, Superhéroes', 'Insomniac Games', NULL, '2023', 1, 4.8),
(42, 5, 'Demon''s Souls (PS5)', 'RPG de acción desafiante', 'Demon''s Souls es un remake espectacular del clásico de PS3. Enfrenta enemigos desafiantes, mejora tus habilidades y derrota poderosos jefes en este juego que requiere habilidad, estrategia y perseverancia.', 49.99, 'https://via.placeholder.com/300x300?text=Demons+Souls', 'RPG de acción, Souls-like', 'Bluepoint Games', NULL, '2020', 1, 4.7),
(43, 5, 'Ratchet & Clank: Rift Apart', 'Aventura interdimensional', 'Viaja entre dimensiones con Ratchet y Clank en esta entrega exclusiva de PS5.', 59.99, 'https://via.placeholder.com/300x300?text=Ratchet+Clank', 'Aventura', 'Insomniac Games', NULL, '2021', 1, 4.8),
(44, 5, 'Returnal', 'Roguelike de ciencia ficción', 'Enfrenta ciclos infinitos en un planeta alienígena hostil.', 49.99, 'https://via.placeholder.com/300x300?text=Returnal', 'Roguelike', 'Housemarque', NULL, '2021', 1, 4.6),
(45, 5, 'Gran Turismo 7', 'Simulación de carreras', 'Compite en circuitos realistas con una gran variedad de autos.', 69.99, 'https://via.placeholder.com/300x300?text=Gran+Turismo+7', 'Simulación', 'Polyphony Digital', NULL, '2022', 1, 4.7),
(46, 5, 'Horizon Forbidden West', 'Aventura de mundo abierto', 'Explora un mundo postapocalíptico lleno de máquinas.', 69.99, 'https://via.placeholder.com/300x300?text=Horizon+FW', 'Aventura', 'Guerrilla Games', NULL, '2022', 1, 4.8),
(47, 5, 'Sackboy: Una aventura a lo grande', 'Plataformas cooperativo', 'Acompaña a Sackboy en una aventura divertida y colorida.', 59.99, 'https://via.placeholder.com/300x300?text=Sackboy', 'Plataformas', 'Sumo Digital', NULL, '2020', 1, 4.5),
(48, 5, 'Ghost of Tsushima: Director''s Cut', 'Acción samurái', 'Vive la historia de Jin Sakai en la isla de Tsushima.', 59.99, 'https://via.placeholder.com/300x300?text=Ghost+of+Tsushima', 'Acción', 'Sucker Punch', NULL, '2021', 1, 4.9),
(49, 5, 'Kena: Bridge of Spirits', 'Aventura mágica', 'Ayuda a los espíritus en un mundo encantado.', 39.99, 'https://via.placeholder.com/300x300?text=Kena', 'Aventura', 'Ember Lab', NULL, '2021', 1, 4.6),
(50, 5, 'Deathloop', 'Shooter en bucle temporal', 'Rompe el ciclo en la isla Blackreef.', 49.99, 'https://via.placeholder.com/300x300?text=Deathloop', 'Shooter', 'Arkane Studios', NULL, '2021', 1, 4.7),
(51, 5, 'Final Fantasy XVI', 'RPG de fantasía', 'La nueva entrega de la saga Final Fantasy.', 69.99, 'https://via.placeholder.com/300x300?text=FFXVI', 'RPG', 'Square Enix', NULL, '2023', 1, 4.8),
-- Categoría 6: Juegos de cartas
(52, 6, 'UNO', 'Juego de cartas clásico', 'UNO es un juego de cartas para toda la familia...', 9.99, 'https://via.placeholder.com/300x300?text=UNO', 'Cartas', NULL, '2-10 jugadores', '1971', 1, 4.7),
(53, 6, 'Magic: The Gathering', 'Juego de cartas coleccionables', 'Magic es el juego de cartas coleccionables más famoso...', 14.99, 'https://via.placeholder.com/300x300?text=Magic', 'Cartas', NULL, '2+ jugadores', '1993', 1, 4.8),
(54, 6, 'Pokémon TCG', 'Juego de cartas de Pokémon', 'Colecciona y combate con cartas de Pokémon...', 12.99, 'https://via.placeholder.com/300x300?text=Pokemon+TCG', 'Cartas', NULL, '2 jugadores', '1996', 1, 4.7),
(55, 6, 'Exploding Kittens', 'Juego de cartas explosivo', 'Evita las cartas explosivas y gana...', 16.99, 'https://via.placeholder.com/300x300?text=Exploding+Kittens', 'Cartas', NULL, '2-5 jugadores', '2015', 1, 4.6),
(56, 6, 'Dobble', 'Juego de observación', 'Encuentra los símbolos iguales antes que los demás...', 11.99, 'https://via.placeholder.com/300x300?text=Dobble', 'Observación', NULL, '2-8 jugadores', '2009', 1, 4.5),
(57, 6, 'Virus!', 'Juego de cartas de virus', 'Compite por erradicar virus en tu cuerpo...', 13.99, 'https://via.placeholder.com/300x300?text=Virus', 'Cartas', NULL, '2-6 jugadores', '2015', 1, 4.5),
(58, 6, 'Cartas contra la humanidad', 'Juego de humor negro', 'Crea las combinaciones más graciosas...', 19.99, 'https://via.placeholder.com/300x300?text=CAH', 'Humor', NULL, '4-20 jugadores', '2011', 1, 4.6),
(59, 6, 'Sushi Go!', 'Juego de cartas rápido', 'Haz la mejor combinación de sushi...', 10.99, 'https://via.placeholder.com/300x300?text=Sushi+Go', 'Cartas', NULL, '2-5 jugadores', '2013', 1, 4.7),
(60, 6, 'The Mind', 'Juego cooperativo de cartas', 'Sin hablar, sincroniza tus cartas...', 9.99, 'https://via.placeholder.com/300x300?text=The+Mind', 'Cooperativo', NULL, '2-4 jugadores', '2018', 1, 4.6),
(61, 6, 'Guillotine', 'Juego de cartas de la Revolución Francesa', 'Colecciona las mejores cabezas...', 8.99, 'https://via.placeholder.com/300x300?text=Guillotine', 'Cartas', NULL, '2-5 jugadores', '1998', 1, 4.4),
(62, 6, 'Bang!', 'Juego de cartas del oeste', 'Sé el sheriff o el forajido...', 15.99, 'https://via.placeholder.com/300x300?text=Bang', 'Cartas', NULL, '4-7 jugadores', '2002', 1, 4.7),
-- Categoría 7: Juegos de rol
(63, 7, 'Dungeons & Dragons', 'Juego de rol clásico', 'Vive aventuras épicas en mundos de fantasía...', 39.99, 'https://via.placeholder.com/300x300?text=DnD', 'Rol', NULL, '2-8 jugadores', '1974', 1, 4.9),
(64, 7, 'Pathfinder', 'Juego de rol de fantasía', 'Explora mundos y combate monstruos...', 34.99, 'https://via.placeholder.com/300x300?text=Pathfinder', 'Rol', NULL, '2-8 jugadores', '2009', 1, 4.7),
(65, 7, 'Cyberpunk Red', 'Juego de rol futurista', 'Sumérgete en el mundo de Cyberpunk...', 29.99, 'https://via.placeholder.com/300x300?text=Cyberpunk+Red', 'Rol', NULL, '2-8 jugadores', '2020', 1, 4.6),
(66, 7, 'La llamada de Cthulhu', 'Juego de rol de horror', 'Investiga misterios y enfréntate a horrores...', 27.99, 'https://via.placeholder.com/300x300?text=Cthulhu', 'Rol', NULL, '2-6 jugadores', '1981', 1, 4.8),
(67, 7, 'Vampiro: La Mascarada', 'Juego de rol de vampiros', 'Vive la noche como un vampiro...', 32.99, 'https://via.placeholder.com/300x300?text=Vampiro', 'Rol', NULL, '2-8 jugadores', '1991', 1, 4.7),
(68, 7, 'Star Wars RPG', 'Juego de rol galáctico', 'Explora la galaxia como Jedi o Sith...', 44.99, 'https://via.placeholder.com/300x300?text=Star+Wars+RPG', 'Rol', NULL, '2-8 jugadores', '2012', 1, 4.6),
(69, 7, 'FATE', 'Sistema de rol genérico', 'Crea cualquier historia con FATE...', 19.99, 'https://via.placeholder.com/300x300?text=FATE', 'Rol', NULL, '2-8 jugadores', '2003', 1, 4.5),
(70, 7, 'Savage Worlds', 'Sistema de rol rápido', 'Acción y aventura en cualquier ambientación...', 24.99, 'https://via.placeholder.com/300x300?text=Savage+Worlds', 'Rol', NULL, '2-8 jugadores', '2003', 1, 4.6),
(71, 7, 'Anima: Beyond Fantasy', 'Rol de fantasía épica', 'Explora un mundo de magia y combate...', 29.99, 'https://via.placeholder.com/300x300?text=Anima', 'Rol', NULL, '2-8 jugadores', '2005', 1, 4.4),
(72, 7, 'Shadowrun', 'Rol ciberpunk', 'Magia y tecnología en un futuro distópico...', 34.99, 'https://via.placeholder.com/300x300?text=Shadowrun', 'Rol', NULL, '2-8 jugadores', '1989', 1, 4.7),
(73, 7, 'Warhammer Fantasy Roleplay', 'Rol de fantasía oscura', 'Sobrevive en el Viejo Mundo...', 39.99, 'https://via.placeholder.com/300x300?text=Warhammer+Fantasy', 'Rol', NULL, '2-8 jugadores', '1986', 1, 4.6),
-- Categoría 8: Juegos móviles
(74, 8, 'Clash Royale', 'Estrategia en tiempo real', 'Compite en batallas rápidas...', 0.00, 'https://via.placeholder.com/300x300?text=Clash+Royale', 'Estrategia', 'Supercell', '1-2 jugadores', '2016', 1, 4.7),
(75, 8, 'Candy Crush Saga', 'Puzzle adictivo', 'Resuelve puzzles y avanza niveles...', 0.00, 'https://via.placeholder.com/300x300?text=Candy+Crush', 'Puzzle', 'King', '1 jugador', '2012', 1, 4.6),
(76, 8, 'Pokémon GO', 'Realidad aumentada', 'Atrapa Pokémon en el mundo real...', 0.00, 'https://via.placeholder.com/300x300?text=Pokemon+GO', 'Aventura', 'Niantic', '1 jugador', '2016', 1, 4.5),
(77, 8, 'Among Us', 'Juego de deducción social', 'Descubre al impostor en la nave...', 0.00, 'https://via.placeholder.com/300x300?text=Among+Us', 'Deducción', 'Innersloth', '4-10 jugadores', '2018', 1, 4.8),
(78, 8, 'PUBG Mobile', 'Battle Royale', 'Sobrevive en partidas multijugador...', 0.00, 'https://via.placeholder.com/300x300?text=PUBG+Mobile', 'Battle Royale', 'Tencent', '1-100 jugadores', '2018', 1, 4.6),
(79, 8, 'Genshin Impact', 'Aventura RPG', 'Explora un mundo abierto mágico...', 0.00, 'https://via.placeholder.com/300x300?text=Genshin+Impact', 'RPG', 'miHoYo', '1-4 jugadores', '2020', 1, 4.7),
(80, 8, 'Brawl Stars', 'Acción multijugador', 'Compite en partidas rápidas...', 0.00, 'https://via.placeholder.com/300x300?text=Brawl+Stars', 'Acción', 'Supercell', '1-10 jugadores', '2018', 1, 4.6),
(81, 8, 'Call of Duty: Mobile', 'Shooter en primera persona', 'Disfruta de la experiencia CoD en móvil...', 0.00, 'https://via.placeholder.com/300x300?text=CoD+Mobile', 'Shooter', 'Activision', '1-100 jugadores', '2019', 1, 4.5),
(82, 8, 'Monument Valley', 'Puzzle artístico', 'Resuelve puzzles en mundos imposibles...', 3.99, 'https://via.placeholder.com/300x300?text=Monument+Valley', 'Puzzle', 'ustwo', '1 jugador', '2014', 1, 4.8),
(83, 8, 'Plague Inc.', 'Simulación de pandemia', 'Crea y evoluciona un virus...', 0.99, 'https://via.placeholder.com/300x300?text=Plague+Inc', 'Simulación', 'Ndemic Creations', '1 jugador', '2012', 1, 4.7),
(84, 8, 'Alto''s Odyssey', 'Aventura de snowboard', 'Surfea dunas y realiza trucos...', 4.99, 'https://via.placeholder.com/300x300?text=Altos+Odyssey', 'Aventura', 'Snowman', '1 jugador', '2018', 1, 4.6),
-- Categoría 9: Juegos retro
(85, 9, 'Tetris', 'Puzzle clásico', 'Tetris es el juego de puzzles más famoso...', 4.99, 'https://via.placeholder.com/300x300?text=Tetris', 'Puzzle', 'Alexey Pajitnov', '1-2 jugadores', '1984', 1, 4.9),
(86, 9, 'Pac-Man', 'Arcade clásico', 'Come puntos y esquiva fantasmas...', 3.99, 'https://via.placeholder.com/300x300?text=Pac-Man', 'Arcade', 'Namco', '1-2 jugadores', '1980', 1, 4.8),
(87, 9, 'Space Invaders', 'Shooter clásico', 'Defiende la Tierra de invasores...', 2.99, 'https://via.placeholder.com/300x300?text=Space+Invaders', 'Shooter', 'Taito', '1 jugador', '1978', 1, 4.7),
(88, 9, 'Donkey Kong', 'Plataformas clásico', 'Ayuda a Mario a rescatar a Pauline...', 3.99, 'https://via.placeholder.com/300x300?text=Donkey+Kong', 'Plataformas', 'Nintendo', '1-2 jugadores', '1981', 1, 4.8),
(89, 9, 'Sonic the Hedgehog', 'Plataformas rápido', 'Corre a toda velocidad con Sonic...', 4.99, 'https://via.placeholder.com/300x300?text=Sonic', 'Plataformas', 'Sega', '1-2 jugadores', '1991', 1, 4.7),
(90, 9, 'Super Mario Bros.', 'Plataformas clásico', 'Salta y rescata a la princesa Peach...', 4.99, 'https://via.placeholder.com/300x300?text=Super+Mario+Bros', 'Plataformas', 'Nintendo', '1-2 jugadores', '1985', 1, 4.9),
(91, 9, 'Street Fighter II', 'Lucha arcade', 'Pelea con luchadores legendarios...', 3.99, 'https://via.placeholder.com/300x300?text=Street+Fighter+II', 'Lucha', 'Capcom', '1-2 jugadores', '1991', 1, 4.8),
(92, 9, 'The Legend of Zelda', 'Aventura clásica', 'Explora Hyrule y derrota a Ganon...', 4.99, 'https://via.placeholder.com/300x300?text=Zelda+NES', 'Aventura', 'Nintendo', '1 jugador', '1986', 1, 4.9),
(93, 9, 'Metroid', 'Aventura espacial', 'Explora planetas y derrota alienígenas...', 3.99, 'https://via.placeholder.com/300x300?text=Metroid', 'Aventura', 'Nintendo', '1 jugador', '1986', 1, 4.7),
(94, 9, 'Castlevania', 'Aventura gótica', 'Enfrenta monstruos en un castillo...', 4.99, 'https://via.placeholder.com/300x300?text=Castlevania', 'Aventura', 'Konami', '1-2 jugadores', '1986', 1, 4.8),
(95, 9, 'Mega Man 2', 'Plataformas desafiante', 'Derrota a los Robot Masters...', 3.99, 'https://via.placeholder.com/300x300?text=Mega+Man+2', 'Plataformas', 'Capcom', '1 jugador', '1988', 1, 4.7),
-- Categoría 10: Accesorios
(96, 10, 'Mando inalámbrico', 'Mando para consolas', 'Mando compatible con varias consolas...', 49.99, 'https://via.placeholder.com/300x300?text=Mando', 'Accesorios', NULL, NULL, '2022', 1, 4.8),
(97, 10, 'Auriculares gaming', 'Auriculares con micrófono', 'Auriculares de alta calidad para juegos...', 59.99, 'https://via.placeholder.com/300x300?text=Auriculares', 'Accesorios', NULL, NULL, '2022', 1, 4.7),
(98, 10, 'Teclado mecánico', 'Teclado para gaming', 'Teclado mecánico retroiluminado...', 89.99, 'https://via.placeholder.com/300x300?text=Teclado', 'Accesorios', NULL, NULL, '2022', 1, 4.8),
(99, 10, 'Ratón gaming', 'Ratón de alta precisión', 'Ratón óptico para juegos competitivos...', 39.99, 'https://via.placeholder.com/300x300?text=Raton', 'Accesorios', NULL, NULL, '2022', 1, 4.7),
(100, 10, 'Alfombrilla RGB', 'Alfombrilla con luces', 'Alfombrilla para ratón con iluminación RGB...', 19.99, 'https://via.placeholder.com/300x300?text=Alfombrilla', 'Accesorios', NULL, NULL, '2022', 1, 4.6),
(101, 10, 'Silla gaming', 'Silla ergonómica', 'Silla cómoda para largas sesiones...', 199.99, 'https://via.placeholder.com/300x300?text=Silla', 'Accesorios', NULL, NULL, '2022', 1, 4.9),
(102, 10, 'Cámara web HD', 'Cámara para streaming', 'Cámara de alta definición para streamers...', 69.99, 'https://via.placeholder.com/300x300?text=Camara', 'Accesorios', NULL, NULL, '2022', 1, 4.7),
(103, 10, 'Micrófono USB', 'Micrófono profesional', 'Micrófono para grabación y streaming...', 89.99, 'https://via.placeholder.com/300x300?text=Microfono', 'Accesorios', NULL, NULL, '2022', 1, 4.8),
(104, 10, 'Volante de carreras', 'Volante para simuladores', 'Volante compatible con juegos de carreras...', 149.99, 'https://via.placeholder.com/300x300?text=Volante', 'Accesorios', NULL, NULL, '2022', 1, 4.7),
(105, 10, 'Tarjeta de captura', 'Captura de vídeo', 'Graba y transmite tus partidas...', 129.99, 'https://via.placeholder.com/300x300?text=Captura', 'Accesorios', NULL, NULL, '2022', 1, 4.6),
(106, 10, 'Base de carga', 'Base para mandos', 'Carga varios mandos a la vez...', 29.99, 'https://via.placeholder.com/300x300?text=Base+de+carga', 'Accesorios', NULL, NULL, '2022', 1, 4.7);
